# Generated by Django 4.1.2 on 2022-10-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoldFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título de Bold features')),
                ('image1', models.ImageField(default='', upload_to='fotos', verbose_name='Imagem do item 1')),
                ('titulo1', models.CharField(max_length=250, verbose_name='Título do item 1')),
                ('descricao1', models.TextField(default='', max_length=500, verbose_name='Descrição para o item 1')),
                ('image2', models.ImageField(default='', upload_to='fotos', verbose_name='Imagem do item 2')),
                ('titulo2', models.CharField(max_length=250, verbose_name='Título do item 2')),
                ('descricao2', models.TextField(default='', max_length=500, verbose_name='Descrição para o item 2')),
                ('image3', models.ImageField(default='', upload_to='fotos', verbose_name='Imagem do item 3')),
                ('titulo3', models.CharField(max_length=250, verbose_name='Título do item 3')),
                ('descricao3', models.TextField(default='', max_length=500, verbose_name='Descrição para o item 3')),
                ('image4', models.ImageField(default='', upload_to='fotos', verbose_name='Imagem do item 4')),
                ('titulo4', models.CharField(max_length=250, verbose_name='Título do item 4')),
                ('descricao4', models.TextField(default='', max_length=500, verbose_name='Descrição para o item 4')),
                ('image5', models.ImageField(default='', upload_to='fotos', verbose_name='Imagem do item 5')),
                ('titulo5', models.CharField(max_length=250, verbose_name='Título do item 5')),
                ('descricao5', models.TextField(default='', max_length=500, verbose_name='Descrição para o item 5')),
                ('image6', models.ImageField(default='', upload_to='fotos', verbose_name='Imagem do item 6')),
                ('titulo6', models.CharField(max_length=250, verbose_name='Título do item 6')),
                ('descricao6', models.TextField(default='', max_length=500, verbose_name='Descrição para o item 6')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=250, verbose_name='Facebook')),
                ('twitter', models.CharField(max_length=250, verbose_name='Twitter')),
                ('gmail', models.CharField(max_length=250, verbose_name='Gmail')),
            ],
        ),
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='fotos', verbose_name='Imagem do celular')),
                ('titulo', models.CharField(max_length=250, verbose_name='Tituo inicial')),
                ('descricao', models.TextField(default='', max_length=500, verbose_name='Mensagem de efeito')),
                ('text_button1', models.CharField(max_length=100, verbose_name='Texto-Botao1')),
                ('text_button2', models.CharField(max_length=100, verbose_name='Texto-Botao2')),
            ],
        ),
        migrations.CreateModel(
            name='MeetLaurel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título de Meet Laurel')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição de Meet Laurel')),
                ('video', models.CharField(max_length=250, verbose_name='Vídeo de Meet Laurel')),
            ],
        ),
        migrations.CreateModel(
            name='StayInTheKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título de Stay in the know')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição de Stay in the know')),
                ('email', models.EmailField(max_length=254)),
                ('text_button', models.CharField(max_length=100, verbose_name='Texto-Botão e-mail')),
            ],
        ),
    ]
