# Generated by Django 4.1.2 on 2022-10-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boldfeatures',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='boldfeatures',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='boldfeatures',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='boldfeatures',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='boldfeatures',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='boldfeatures',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='gmail',
        ),
        migrations.AddField(
            model_name='contato',
            name='google',
            field=models.CharField(default='', max_length=250, verbose_name='Google'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='image',
            field=models.ImageField(default='', upload_to='fotos', verbose_name='Imagem'),
        ),
    ]
