# Generated by Django 4.1.2 on 2022-10-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_remove_boldfeatures_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('text_button', models.CharField(max_length=100, verbose_name='Texto-Botão e-mail')),
            ],
        ),
        migrations.RemoveField(
            model_name='stayintheknow',
            name='email',
        ),
        migrations.RemoveField(
            model_name='stayintheknow',
            name='text_button',
        ),
    ]
