# Generated by Django 4.1.2 on 2022-10-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_enviaremail_delete_earlyaccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviaremail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
